### ISSUE TITLE
Readme file mentions PSK, but I guess it's FSK

### ISSUE THREAD

**Issue by pu3hag** [lu7did/ADX-rp2040#2]
Hi Pedro, this is PU3HAG Huelbe from Porto Alegre, Brazil.

At file Readme.md, there's a paragraph where it reads:

> process incoming audio signals to derive that is the PSK tone

Based on previous and following paragraphs in your presentation, I think it should read FSK, instead of PSK.

73 e Boas Festas!

**Comment by lu7did** [comment]
Yes, also “that is” should be “what is” thank
You for pointing out.

73 e Boas Festas, Pedro LU7DZ
