### ISSUE TITLE
Problem load.

### ISSUE THREAD

**Issue by avemirat** [lu7did/ADX-rp2040#3]
Hi, thanks for your project, but I'm not sure how to load the code with Arduino and r-pico.  When I load the code it doesn't compile, I have installed the correct libraries but it doesn't load the code, could you explain in more detail.  Thanks

**Comment by lu7did** [comment]
Hi, you should ensure the libraries stated in the README.md file are installed correctly. What errors are you getting? 73

**Comment by avemirat** [comment]
Hola Pedro , mi nombre es Agustín soy EA1DIW, gracias por la respuesta , no
recuerdo el error que me da al cargar el código, no estoy actualmente en mi
casa , pero lo miraré y le contestare . Probe el primer código el que no
lleva la pantalla LCD y funcionó correctamente. Entiendo que puedo cargar
el código directamente ya compilado con la extensión uf2 , lo intentaré
también .
Otra cosa es posible usar una pantalla ili 9341?
Gracias por su tiempo , probaré en cuanto pueda y le comunicaré mis
resultados.
Muchas gracias y un abrazo

**Comment by lu7did** [comment]
Hola, la única pantalla testeada es la IL9488, otras pantallas son mas pequeñas (requiriendo una reconfiguración de los controles gráficos) o mas lentas (lo que interfiere con la decodificación FT8). He tenido reportes de problemas con otro tipo de pantallas pero no los he podido abordar al no poder reproducirlos.

73 de Pedro, LU7DZ

**Comment by avemirat** [comment]
Gracias por la información
73

**Comment by avemirat** [comment]
Hola Pedro , tengo  funcionando el RDX, pero la pantalla no está calibrada
con el lápiz , como puedo calibrar la pantalla porque hay una desviación
muy importante y no es posible acceder los menús , he mirado pero no
encuentro la posibilidad de ajustarlo.
Gracias y un excelente trabajo.

**Comment by lu7did** [comment]
Hola, el firmware tiene un calibración default. Hay que agregar en el futuro una para cada caso.

saludos Pedr
